name: Publish Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/simple-logger
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Build and validate
        run: npm run build

      - name: Get tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
      - name: Create GitHub Release
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          
          # Extract changelog content for this version
          CHANGELOG_CONTENT=$(awk "/^## \[${VERSION#v}\]/{flag=1; next} /^## \[/{flag=0} flag" CHANGELOG.md | sed '/^$/d' | head -20)
          
          # Create release with changelog content
          if [ -n "$CHANGELOG_CONTENT" ]; then
            gh release create "$VERSION" \
              --title "$VERSION" \
              --notes "$CHANGELOG_CONTENT"
          else
            gh release create "$VERSION" \
              --title "$VERSION" \
              --notes "Release $VERSION"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}